### ISSUE TITLE
test for bit-for-bit reproduction with to/from yaml

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#112] opened 2024-09-04 22:52 UTC
I am still unable to get a bit-for-bit reproduction of tides, surface forcing, initial and boundary conditions by saving to netcdf and yaml, then loading from yaml, saving to netcdf again and comparing the checksums of the two netcdf files (works for the grid though!)

We should aim to test for this.

**Comment by NoraLoose** [comment] 2024-09-24 21:47
This bit-by-bit reproducibility test was implemented before we merged #140, but I had to comment it out for reasons explained in #142. I think it is okay to close this issue because we have #142 open. Agreed @dafyddstephenson?

**Closed** 2024-09-27 14:28 UTC
Labels: testing
